version: '3'
services:
  app:
    image: node:latest
    container_name: my-app
    working_dir: /home/app
    volumes:
      - ./:/home/app
    ports:
      - '4000:4000'
    command: ['npm', 'run', 'start:dev']
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: 'redis:alpine'
    container_name: redis-server
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
